---
abstract: 'IMAP client library for AnyEvent'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-IMAP
no_index:
  directory:
    - inc
provides:
  AnyEvent::IMAP:
    file: lib/AnyEvent/IMAP.pm
    version: 0.04
  Mail::IMAP::Address:
    file: lib/Mail/IMAP/Address.pm
    version: 0
  Mail::IMAP::Envelope:
    file: lib/Mail/IMAP/Envelope.pm
    version: 0
  Mail::IMAP::Util:
    file: lib/Mail/IMAP/Util.pm
    version: 0
requires:
  AnyEvent: 7
  Mouse: 0.97
  Net::SSLeay: 0
  Object::Event: 1.23
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
